runtime: nodejs
env: flex
# secure: always

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  SQL_USER: webapp
  SQL_PASSWORD: arches123
  SQL_DATABASE: prod
  INSTANCE_CONNECTION_NAME: arches-224720:us-east1:arches

beta_settings:
  cloud_sql_instances: arches-224720:us-east1:arches